// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fnjqjifeefhqxbaeqwzy.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuanFqaWZlZWZocXhiYWVxd3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MTE3OTQsImV4cCI6MjA0ODI4Nzc5NH0.fEEhC3-hfYcYADXF2JCZQhq6-TuX88QhdQH-n9o6z1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);